
import { Tool } from './types';

export const ALL_TOOLS: Tool[] = [
  {
    "id": "case-converter",
    "name": "Case Converter",
    "description": "Convert text to uppercase, lowercase, etc.",
    "link": "/case-converter",
    "category": "Utilities",
    "icon": "CaseUpper",
    "isEnabled": true,
    "order": 0,
    "authRequired": false
  },
  {
    "id": "password-generator",
    "name": "Password Generator",
    "description": "Create secure, random passwords.",
    "link": "/password-generator",
    "category": "Security",
    "icon": "Lock",
    "isEnabled": true,
    "order": 1,
    "authRequired": false
  },
  {
    "id": "qr-generator",
    "name": "QR Code Generator",
    "description": "Create custom QR codes for URLs or text.",
    "link": "/qr-generator",
    "category": "Utilities",
    "icon": "QrCode",
    "isEnabled": true,
    "order": 2,
    "authRequired": false
  },
  {
    "id": "json-formatter",
    "name": "JSON Formatter",
    "description": "Format, validate, and beautify JSON data.",
    "link": "/json-formatter",
    "category": "Development",
    "icon": "Braces",
    "isEnabled": true,
    "order": 3,
    "authRequired": false
  },
  {
    "id": "lorem-ipsum-generator",
    "name": "Lorem Ipsum Generator",
    "description": "Generate placeholder text for your designs.",
    "link": "/lorem-ipsum-generator",
    "category": "Content",
    "icon": "FileText",
    "isEnabled": true,
    "order": 4,
    "authRequired": false
  },
  {
    "id": "color-converter",
    "name": "Color Converter",
    "description": "Convert between HEX, RGB, and HSL values.",
    "link": "/color-converter",
    "category": "Design",
    "icon": "Palette",
    "isEnabled": true,
    "order": 5,
    "authRequired": false
  },
  {
    "id": "image-compressor",
    "name": "Image Compressor",
    "description": "Reduce file size of JPG & PNG images.",
    "link": "/image-compressor",
    "category": "Image",
    "icon": "Minimize2",
    "isEnabled": true,
    "order": 6,
    "authRequired": true
  },
  {
    "id": "markdown-editor",
    "name": "Markdown Editor",
    "description": "Write and preview Markdown in real-time.",
    "link": "/markdown-editor",
    "category": "Content",
    "icon": "FileSignature",
    "isEnabled": true,
    "order": 7,
    "authRequired": false
  },
  {
    "id": "unit-converter",
    "name": "Unit Converter",
    "description": "Convert length, weight, temperature, etc.",
    "link": "/unit-converter",
    "category": "Utilities",
    "icon": "Ruler",
    "isEnabled": true,
    "order": 8,
    "authRequired": false
  },
  {
    "id": "word-counter",
    "name": "Word Counter",
    "description": "Count words, characters, and sentences.",
    "link": "/word-counter",
    "category": "Content",
    "icon": "FileJson2",
    "isEnabled": true,
    "order": 9,
    "authRequired": false
  },
  {
    "id": "url-encoder-decoder",
    "name": "URL Encoder & Decoder",
    "description": "Encode or decode special characters in URLs.",
    "link": "/url-encoder-decoder",
    "category": "Development",
    "icon": "Link",
    "isEnabled": true,
    "order": 10,
    "authRequired": false
  },
  {
    "id": "image-resizer",
    "name": "Image Resizer",
    "description": "Resize images to specific dimensions online.",
    "link": "/image-resizer",
    "category": "Image",
    "icon": "Crop",
    "isEnabled": true,
    "order": 11,
    "authRequired": true
  },
  {
    "id": "base64-encoder",
    "name": "Base64 Encoder & Decoder",
    "description": "Encode or decode text to Base64 format.",
    "link": "/base64-encoder",
    "category": "Development",
    "icon": "Binary",
    "isEnabled": true,
    "order": 12,
    "authRequired": false
  },
  {
    "id": "hash-generator",
    "name": "Hash Generator",
    "description": "Generate MD5, SHA-1, SHA-256 hashes.",
    "link": "/hash-generator",
    "category": "Security",
    "icon": "Fingerprint",
    "isEnabled": true,
    "order": 13,
    "authRequired": false
  },
  {
    "id": "favicon-generator",
    "name": "Favicon Generator",
    "description": "Create a favicon from any image.",
    "link": "/favicon-generator",
    "category": "Image",
    "icon": "Heart",
    "isEnabled": true,
    "order": 14,
    "authRequired": true
  },
  {
    "id": "html-minifier",
    "name": "HTML Minifier",
    "description": "Minify and compress HTML code.",
    "link": "/html-minifier",
    "category": "Development",
    "icon": "FileCode",
    "isEnabled": true,
    "order": 15,
    "authRequired": false
  },
  {
    "id": "css-minifier",
    "name": "CSS Minifier",
    "description": "Minify and optimize CSS stylesheets.",
    "link": "/css-minifier",
    "category": "Development",
    "icon": "FileCode2",
    "isEnabled": true,
    "order": 16,
    "authRequired": false
  },
  {
    "id": "javascript-minifier",
    "name": "JavaScript Minifier",
    "description": "Compress and minify JavaScript files.",
    "link": "/javascript-minifier",
    "category": "Development",
    "icon": "FileCode2",
    "isEnabled": true,
    "order": 17,
    "authRequired": false
  },
  {
    "id": "meta-tag-generator",
    "name": "Meta Tag Generator",
    "description": "Create SEO-friendly meta tags for websites.",
    "link": "/meta-tag-generator",
    "category": "SEO",
    "icon": "Code",
    "isEnabled": true,
    "order": 18,
    "authRequired": false
  },
  {
    "id": "open-graph-generator",
    "name": "Open Graph Generator",
    "description": "Generate Open Graph tags for social sharing.",
    "link": "/open-graph-generator",
    "category": "SEO",
    "icon": "Share2",
    "isEnabled": true,
    "order": 19,
    "authRequired": false
  },
  {
    "id": "slug-generator",
    "name": "Slug Generator",
    "description": "Convert text into SEO-friendly slugs.",
    "link": "/slug-generator",
    "category": "SEO",
    "icon": "Globe",
    "isEnabled": true,
    "order": 20,
    "authRequired": false
  },
  {
    "id": "emoji-picker",
    "name": "Emoji Picker",
    "description": "Search and copy emojis instantly.",
    "link": "/emoji-picker",
    "category": "Content",
    "icon": "Smile",
    "isEnabled": true,
    "order": 21,
    "authRequired": false
  },
  {
    "id": "gradient-generator",
    "name": "Gradient Generator",
    "description": "Create custom CSS gradients.",
    "link": "/gradient-generator",
    "category": "Design",
    "icon": "Paintbrush",
    "isEnabled": true,
    "order": 22,
    "authRequired": false
  },
  {
    "id": "box-shadow-generator",
    "name": "Box Shadow Generator",
    "description": "Generate CSS box shadows visually.",
    "link": "/box-shadow-generator",
    "category": "Design",
    "icon": "BoxSelect",
    "isEnabled": true,
    "order": 23,
    "authRequired": false
  },
  {
    "id": "border-radius-generator",
    "name": "Border Radius Generator",
    "description": "Visualize and generate CSS border-radius.",
    "link": "/border-radius-generator",
    "category": "Design",
    "icon": "Square",
    "isEnabled": true,
    "order": 24,
    "authRequired": false
  },
  {
    "id": "regex-tester",
    "name": "Regex Tester",
    "description": "Test and debug regular expressions.",
    "link": "/regex-tester",
    "category": "Development",
    "icon": "Scan",
    "isEnabled": true,
    "order": 25,
    "authRequired": false
  },
  {
    "id": "html-entity-converter",
    "name": "HTML Entity Converter",
    "description": "Convert text to HTML entities and vice versa.",
    "link": "/html-entity-converter",
    "category": "Development",
    "icon": "Code2",
    "isEnabled": true,
    "order": 26,
    "authRequired": false
  },
  {
    "id": "icon-finder",
    "name": "Icon Finder",
    "description": "Search and download icons.",
    "link": "/icon-finder",
    "category": "Design",
    "icon": "Search",
    "isEnabled": true,
    "order": 27,
    "authRequired": false
  },
  {
    "id": "text-diff-checker",
    "name": "Text Diff Checker",
    "description": "Compare two texts and highlight differences.",
    "link": "/text-diff-checker",
    "category": "Content",
    "icon": "GitCompareArrows",
    "isEnabled": true,
    "order": 28,
    "authRequired": false
  },
  {
    "id": "pdf-merger",
    "name": "PDF Merger",
    "description": "Merge multiple PDF files into one.",
    "link": "/pdf-merger",
    "category": "PDF",
    "icon": "FilePlus",
    "isEnabled": true,
    "order": 29,
    "authRequired": true
  },
  {
    "id": "pdf-splitter",
    "name": "PDF Splitter",
    "description": "Split PDF files into separate pages.",
    "link": "/pdf-splitter",
    "category": "PDF",
    "icon": "FileMinus",
    "isEnabled": true,
    "order": 30,
    "authRequired": false
  },
  {
    "id": "image-to-pdf",
    "name": "Image to PDF",
    "description": "Convert JPG, PNG, and other images to PDF.",
    "link": "/image-to-pdf",
    "category": "PDF",
    "icon": "FileImage",
    "isEnabled": true,
    "order": 31,
    "authRequired": false
  },
  {
    "id": "speech-to-text",
    "name": "Speech to Text",
    "description": "Transcribe audio to text in real-time.",
    "link": "/speech-to-text",
    "category": "Utilities",
    "icon": "Mic",
    "isEnabled": true,
    "order": 32,
    "authRequired": false
  },
  {
    "id": "text-to-speech",
    "name": "Text to Speech",
    "description": "Convert text to life-like speech.",
    "link": "/text-to-speech",
    "category": "Utilities",
    "icon": "Volume2",
    "isEnabled": true,
    "order": 33,
    "authRequired": false
  },
  {
    "id": "github-to-jsdelivr-converter",
    "name": "GitHub to jsDelivr Converter",
    "description": "Convert GitHub file URLs to jsDelivr CDN links.",
    "link": "/github-to-jsdelivr-converter",
    "category": "Development",
    "icon": "GitCompareArrows",
    "isEnabled": true,
    "order": 34,
    "authRequired": false
  }
];
